### ISSUE TITLE
Multiple remotegraphqldatasource

### ISSUE THREAD

**Issue by cyril36** [profusion/apollo-federation-file-upload#15]
I have a datasource that i have implemented to modify the header before sending the header to my micro services
but I also want to add FileUploadDataSource pointing to my micro-services.

is it possible to merge the 2 DataSources?
Can we add multiple datasources to the same service?

**Comment by cabelitos** [comment]
Hello @cyril36 , how are you? Thanks for the interest in this package. 

So, you can't use two data sources at the same time. However you can use inheritance, but please remember to call the parents method, making it possible for the FileUploadDataSource to work properly. You can code something like this.

```js

class MySource extends FileUploadDataSource {

willSendRequest(args) {
 super.willSendRequest(args);
   args.request.http.headers.set('MyHeader', 'value');
    }
}
```

Then  MySource where needed. In case you have a more complex data source I can work with you to expose the functions data the FileUploadDataSource uses, then you can use it directly

**Comment by Tibiritabara** [comment]
Hey @cabelitos I'm setting up this package and I am running with the same issue as @cyril36 . Im trying to authenticate and leverage this package, basically merging the functionality, but I cannot find a way to do it, as the super throws me "Cannot invoke an object which is possibly 'undefined'.ts(2722)"

Im sorry if this is a dumb question, my experience with typescript is not that extended.

```typescript
import FileUploadDataSource from '@profusion/apollo-federation-upload';

export default class CustomDataSource extends FileUploadDataSource {

    willSendRequest(args) {
        super.willSendRequest(args);
        args.request.http.headers.set('MyHeader', 'value');
    }
}
```

Thank you so much in advance

**Comment by cabelitos** [comment]
Which object is possibly undefined? In this case we would add an if checking if it's valid, before trying to call it. If I'm not mistaken the headers and http object may be null. I don't remember by heart. Gotta check the typing.

**Comment by cabelitos** [comment]
I'm closing this one, since it's not an issue on our side or an issue per se.
