### ISSUE TITLE
File uploading not working at all - maximum call stack size exceeded

### ISSUE THREAD

**Issue by Ancient-Dragon** [profusion/apollo-federation-file-upload#27]
Hi there,

I'm trying to use this package with a spring dgs graphql server. If I was to just connect directly to my spring server everything works fine, but as soon as I try and use my federation apollo server with this library, setup as the read me states (using FileUploadDataSource.default instead because it appears readme is out of date) I get the following error on the federation server:
```
internal/fs/streams.js:131
  _openReadFs(this);
  ^
RangeError: Maximum call stack size exceeded
```
package.json contains:
```
 "@apollo/federation": "0.25.2",
    "@apollo/gateway": "0.33.0",
    "@profusion/apollo-federation-upload": "2.2.2",
    "apollo-server": "2.25.0",
    "graphql": "15.5.1",
```
Has anyone seen this before / know how to solve this?

(Also I'm using the vue-apollo client on the frontend with the apollo-upload-client)

**Comment by Ancient-Dragon** [comment]
Hey, @cabelitos I've seen you've been able to help others on this library don't suppose you can shed some insight into the issue I'm having above I would greatly appreciate it

**Comment by cabelitos** [comment]
hello @Ancient-Dragon I'll take a look. But I guess you're using node 14, right?

**Comment by Ancient-Dragon** [comment]
Thank you so much @cabelitos! Yes I am.

**Comment by cabelitos** [comment]
Since this is the case, there's a known bug from fs-capacitor (which is a dep for apollo's file upload) that causes this crash on node14.
Since apollo-server explicitly bundles graphql-upload v8, you'll have to manually disable apollo's library and explicitly use the newer version. Note this problem is not related to this package and it goes outside our control to fix this.

However, here's a snippet that tells you more about the problem and how to fix it.

https://github.com/apollographql/apollo-server/blob/release-3.0/docs/source/data/file-uploads.md <- this docs are for apollo-server v3, but they still apply for v2
The issue: https://github.com/jaydenseric/graphql-upload/issues/221

**Comment by Ancient-Dragon** [comment]
So I tried that in conjunction with this library but I get the error: Expected type org.springframework.web.multipart.MultipartFile but was java.util.LinkedHashMap which is what I was getting without any library / file upload stuff

Here is the code:

```
const { ApolloServer } = require('apollo-server-express');
const { ApolloGateway } = require('@apollo/gateway');
const FileUploadDataSource = require('@profusion/apollo-federation-upload');
const express = require('express');
const { graphqlUploadExpress } = require('graphql-upload');

async function startApolloServer() {
  const server = new ApolloServer({
    gateway: new ApolloGateway({
      // Add this line in order to support file uploads.
      buildService: ({ url }) => new FileUploadDataSource.default({ url, useChunkedTransfer: false }),
      serviceList: [
        { name: 'java', url: 'http://localhost:8090/graphql' },
        { name: 'shows', url: 'http://localhost:8091/graphql' },
      ],
    }),
    subscriptions: false,
    uploads: false,
  });

  await server.start();
  const app = express();
  app.use(graphqlUploadExpress({ maxFileSize: 10000000, maxFiles: 10 }));
  server.applyMiddleware({
    app,
  });
  await new Promise((resolve) => app.listen({ port: 8100 }, resolve));
  console.log(`🚀 Server ready at http://localhost:8100${server.graphqlPath}`);
  return { server, app };
}

startApolloServer()
  .then((r) => console.log('promise resolved'));
```

**Comment by cabelitos** [comment]
@Ancient-Dragon Well, I can not help you on the java side. What's this java code? Is your apollo-server trying to end data to it?

**Comment by cabelitos** [comment]
I think that a good approach is try to isolate the problem. After your change, does the apollo-server correctly receives the file data?

**Comment by Ancient-Dragon** [comment]
@cabelitos, no worries on the java code. I was more looking for help with this. Clearly seems to be something to do with the apollo gateway / server. I assume that they this apollo gateway/server act as a proxy to the true graphql server (in this case java).

**Comment by cabelitos** [comment]
@Ancient-Dragon are you able to debug this apollo server? you'll need to do something similar to what I did in here for this library. Which is to forward the uploaded data to your graphql server (the java one)

**Comment by Ancient-Dragon** [comment]
@cabelitos yes I can debug the apollo server. I'm not quite sure what you mean with what you did here in this lib? Could you go into a little more detail? Are you expecting me to create me own FileUploadDataSource?

**Comment by Ancient-Dragon** [comment]
@cabelitos I think I noticed something. When I send the request from my frontend my form data contains this: {"1": ["variables.files.0"]}
Whereas the request your library is sending as: {"0":["variables.files.0.promise"]}

**Comment by Ancient-Dragon** [comment]
I got there in the end I believe (by changing my node modules file) - the changes I had to make where:
in the addToDataToForm method (didn't look at the chunked version):
``` 
form.append((i + 1).toString(), fileData, { // this line
        contentType,
        filename,
        knownLength: fileData.length,
    });
```
in process files: 
```
fileVariables.forEach(([variableName]) => {
                lodash_set_1.default(variables, variableName.replace('.promise', ''), null); // This line
            });
...

const resolvedFiles = yield Promise.all(fileVariables.map(([variableName, file], i) => __awaiter(this, void 0, void 0, function* () {
                const fileUpload = yield file;
                fileMap[i + 1] = [`variables.${variableName.replace('.promise', "")}`]; // This line
                return fileUpload;
            })));
```
I guess my question now is should this belong in your library?

**Comment by cabelitos** [comment]
@Ancient-Dragon This is definitely an error on our side. I'm really sorry about this, I've fixed the problem in here: https://github.com/profusion/apollo-federation-file-upload/pull/28

It looks like that the graphql-upload is now reporting the Upload class directly instead of a Promise<FileUpload>

**Comment by Ancient-Dragon** [comment]
No worries, appreciate the really quick fix! Thank you. Can you let me know when you merge and publish and I'll give it a go :) and let you know how it works

**Comment by Ancient-Dragon** [comment]
I did notice you didn't increment values in the array (I'm not sure how much difference this really makes as I didn't test it on my end)

**Comment by cabelitos** [comment]
@Ancient-Dragon Thank you for reporting the problem and your patience. I've published a new version on NPM.
The new version is 2.2.3 (https://www.npmjs.com/package/@profusion/apollo-federation-upload). Please let me know if this fix the problem for you.

About the array increment. No need to manually increment, since the map handler already provides the updated `i` value.

**Comment by Ancient-Dragon** [comment]
@cabelitos just tested it out, looks to be working perfectly thank you so much for this!
