### ISSUE TITLE
using apollo federation file upload

### ISSUE THREAD

**Issue by jaymarkjairi** [profusion/apollo-federation-file-upload#35]
this is my code
import {
ApolloGateway, 
// RemoteGraphQLDataSource //replace by FileUploadDataSource from @profusion/apollo-federation-upload for file upload
} from '@apollo/gateway'
import FileUploadDataSource from '@profusion/apollo-federation-upload'
const gateway = new ApolloGateway({ //RemoteGraphQLDataSource 
   serviceList, //port:4010
   buildService: ({ url }) => new FileUploadDataSource({ 
   url, useChunkedTransfer: true }),
   useChunkedTransfer: true,
})

this is the result in using it with the apollo gateway
![image](https://user-images.githubusercontent.com/41337290/130348472-496cb7e7-7e03-4f40-bf31-f51af53fb354.png)

it shows this error BadRequestError: Missing multipart field ‘operations’.

but when directly uploading it to the subgraph this is the result 
![image](https://user-images.githubusercontent.com/41337290/130348531-dab96440-73bb-4381-9a87-c9d653cc8c62.png)

either of the RemoteGraphQLDataSource  and FileUploadDataSource  has the same result, can you give me some advise in how I can fix this kind of issue? thank you

**Comment by cabelitos** [comment]
Not really sure what's happening, since I can't see the whole code. However I created a simple setup which works like a charm:
https://codesandbox.io/s/silent-leftpad-0j63m?file=/index.js

Let me know if you still have problems.
If you still have, please share a reproducible example.

**Comment by jaymarkjairi** [comment]
this is my code
![2](https://user-images.githubusercontent.com/41337290/130828562-c9ecc008-34b8-46b6-b13d-1b23070b03ce.PNG)

![3](https://user-images.githubusercontent.com/41337290/130828446-24841ec4-3362-4d61-8e4d-a6c944a0b5a3.PNG)

inside the server list

![1](https://user-images.githubusercontent.com/41337290/130828612-00d9a263-f426-4a9b-b955-c62b428cd858.PNG)

resolver
![7](https://user-images.githubusercontent.com/41337290/130828864-1a75ce79-87a9-4cd8-bdaa-1819932bbbfb.PNG)

![8](https://user-images.githubusercontent.com/41337290/130829307-0ae12d1d-a556-46c6-90ea-1db50c57d714.PNG)

apollo-gateway
![image](https://user-images.githubusercontent.com/41337290/130830530-104a1548-ae12-4e5b-a33e-322256069bd0.png)

then load serverlist
![5](https://user-images.githubusercontent.com/41337290/130829615-c03f0d2d-261d-4339-971d-cebf0ebb6ba3.PNG)


![6](https://user-images.githubusercontent.com/41337290/130830019-5028c44d-6313-4e48-bb22-f78b46baef9e.PNG)


then that error will comes, what should I do? thank you for helping

**Comment by jaymarkjairi** [comment]
Thank you I can upload now I add `uploads:false` in apollo-sever-express 
 but sometimes it give me errorr, I think that this is not cover by apollo federation file upload but can you help me where I can get help about this...  

this is the error
![image](https://user-images.githubusercontent.com/41337290/131026416-5d02cea8-0a2e-48a0-9e14-096f2e50c2b9.png)

and I apply the same fix in Apollo server and gives me this error 
![image](https://user-images.githubusercontent.com/41337290/131027117-5078661b-9435-4b6c-ae0f-7a05a8244f99.png)


this is my code

![image](https://user-images.githubusercontent.com/41337290/131027778-6fe21d7e-facb-4f64-ba75-b1585e0115cf.png)
inside my server list
![image](https://user-images.githubusercontent.com/41337290/131027842-2b1bde74-b4ba-45fd-b7f0-eec9422e4ac2.png)


and this is my code in apollo server express area

![image](https://user-images.githubusercontent.com/41337290/131028010-1352a980-206d-4f39-8d53-8f89aa3943be.png)

I think that I need to apply middle midleware in apollo server area, but when I use this line `server.applyMiddleware()` it will suggest me to use apollo server express
![image](https://user-images.githubusercontent.com/41337290/131028662-6f69fe2d-2df0-4762-8cc4-a6ff8b4bad83.png)

![image](https://user-images.githubusercontent.com/41337290/131028437-4a5a1b41-d206-48cb-a462-5d5e94263fe9.png)
thank you so much for your'e help..
