### ISSUE TITLE
Apollo Federation v2 Support

### ISSUE THREAD

**Issue by douglas-wang** [profusion/apollo-federation-file-upload#50]
Hi.

Apollo finally published federation v2 and any roadmap plan to support it?

https://www.apollographql.com/docs/federation/

Cheers

**Comment by cabelitos** [comment]
@douglas-wang Thank you for your issue. Please check #51, once it's merged I'll ship a new release to NPM.

**Comment by douglas-wang** [comment]
@cabelitos that's a great news. Thanks for letting me know.
Looking forward to the new release 🎉

**Comment by cabelitos** [comment]
Hello @douglas-wang, version 4.0.0 now publish to NPM. Please let me know if it helps you. Thank you very much.

https://www.npmjs.com/package/@profusion/apollo-federation-upload

**Comment by douglas-wang** [comment]
This is great news. Thank you, @cabelitos.
