### ISSUE TITLE
Review release 4.1 and create tests for it

### ISSUE THREAD

**Issue by oliveirarleo** [profusion/apollo-federation-file-upload#66]
## Problem related to enhancement request
https://github.com/profusion/apollo-federation-file-upload/pull/55 needs reviewing, testing and create jest tests for it.

## Acceptance criteria
- [x] PR reviewed
- [ ] new release tested
- [ ] jest tests created

**Comment by veimox** [comment]
❤️

**Comment by oliveirarleo** [comment]
fixed by https://github.com/profusion/apollo-federation-file-upload/pull/67
